twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        categorie_repository: '@App\Repository\CategorieRepository'
        categorie_service: '@App\Repository\CategorieRepository'
        annonce_repository: '@App\Repository\AnnonceRepository'
        annonce_service: '@App\Repository\AnnonceRepository'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
